### ISSUE TITLE
Adding subscription rules is very slow.

### ISSUE THREAD

**Issue by mattdone01** [Particular/NServiceBus.AzureServiceBus#592] opened 2017-07-21 00:16 UTC
Checking and adding subscription rules when connected to Azure service bus is very slow. This is due to the fact that there is no way to check if a rule exists and you have to handle and exception to add the rule. Microsoft has just approved and committed a pull request https://github.com/Azure/azure-service-bus-dotnet/pull/192 that should fix this issue. 

The code is at Line 82 of AzureServiceBusForwardingSubscriptionCreator. MS have now added GetRulesAsync() which should remove the need to handle an exception for an add. Can someone please confirm my assumptions is correct. Thanks

**Comment by SeanFeldman** [comment] 2017-07-21 00:19
@mattdone01the referenced PR is still a WIP. Also, that client is the new
client repo, which has not GA-ed yet 🙂

**Comment by SeanFeldman** [comment] 2017-07-21 00:27
For the current client, I've [raised an issue](https://github.com/Azure/azure-service-bus/issues/16) with the PG.
Will be more than happy if you'd think it up and so your comment as well.

**Comment by mattdone01** [comment] 2017-08-07 04:15
Hi Sean, Is there a path to upgrade NSB.ASB transport to the new Microsoft.Azure.ServiceBus library. It went RC1 the other day. I'd be happy to help out if required.

**Comment by SeanFeldman** [comment] 2017-08-07 06:26
Thank you @mattdone01. Very kind of you to offer help and it's appreciated.
The path to upgrade is not as straight as we'd like it to be. First, there's not support for [`SendsAtomicWithReceive`](https://docs.particular.net/transports/azure-service-bus/understanding-transactions-and-delivery-guarantees?version=asb_8) transport transactions. It's only going to show up in the [2.0.0](https://github.com/Azure/azure-service-bus-dotnet/issues/6) of the new ASB client. In addition to that, there are other things that stay in the way, such as [no support for HTTPS](https://github.com/Azure/azure-service-bus-dotnet/issues/102) connectivity mode. And there's also a very significant issue that will affect [wire compatibility](https://github.com/Azure/azure-service-bus-dotnet/issues/239) NServiceBus cannot break.

Given all these, the upgrade is unfortunately not a simple update. We're looking into the options internally to ensure that we enable our customers to be able to run on the new client w/o compromising trust and support of the existing customers that expect things to work w/o surprises.

A side note on RC1 - be careful if you intend to use it in production. It is **not** a final version and there will be issues that would need to be resolves (like [this one](https://github.com/Azure/azure-service-bus-dotnet/pull/256), or [this one](https://github.com/Azure/azure-service-bus-dotnet/pull/245), or [this one](https://github.com/Azure/azure-service-bus-dotnet/pull/241)).

**Comment by mattdone01** [comment] 2017-08-07 06:44
Thanks Sean. Appreciate the response. When we start a console it takes about 2 minutes to start up as we have about 25 event handlers (CQRS implementation). I've debugged the NSB code and the bulk of the time is taken when checking for the existence of a rule (It throws an exception to check existence). I know it's not the best code but I don't suppose we could get a flag to bypass any rule check. Something like transport.ByPassRuleCheck with it obviously set to false as the default. That would be a big help. Thanks Sean.

**Comment by SeanFeldman** [comment] 2017-08-07 06:49
Is disabling installers and scripting your entities a viable option?
(Removing `endpointConfiguration.EnableInstallers();` from your configuration code).

**Comment by danielmarbach** [comment] 2017-08-07 06:51
And run without managed rights if you're topology doesn't change that often. This will bypass all those checks as well. See https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/TopologyCreator.cs#L34

**Comment by mattdone01** [comment] 2017-08-07 07:06
Hi Daniel,
 Thanks for that. How do you set NSB to "run without managed rights". Thanks.
Matt

**Comment by danielmarbach** [comment] 2017-08-07 07:34
I'm assuming here you are using Shared access policies. Create a new policy and do not grant the manage rights and use that in the connection string. 

![image](https://user-images.githubusercontent.com/174258/29016663-9c051ea6-7b53-11e7-8def-cb2d6d4e37cc.png)

**Comment by mattdone01** [comment] 2017-08-07 07:53
That just throws an "UnauthorizedAccessException" : 'Topology creation requires manage rights, but no manage rights could be found for the following namespace(s): `default`' and the bus fails to start.

**Comment by danielmarbach** [comment] 2017-08-07 07:56
You need at least this version

https://github.com/Particular/NServiceBus.AzureServiceBus/releases/tag/7.2.3

and you need to disable the installers (remove `EnableInstallers()`) from your configuration. Does that work?

**Comment by mattdone01** [comment] 2017-08-07 10:09
I am using NServiceBus.Azure.Transports.WindowsAzureServiceBus.7.2.6
With the following Config
` var configuration = new EndpointConfiguration(UniqueQueueAddress.EndpointName());
            var assemblyScanner = configuration.AssemblyScanner();
            assemblyScanner.ExcludeAssemblies("PostSharp.dll");

            configuration.UseContainer<AutofacBuilder>(customizations =>
            {
                customizations.ExistingLifetimeScope(container);
            });
           
            NServiceBus.Logging.LogManager.Use<NLogFactory>();

            configuration.SendFailedMessagesTo("error");
            configuration.UsePersistence<InMemoryPersistence>();
            configuration.UseSerialization<NewtonsoftSerializer>();
            //configuration.EnableInstallers();
            var transport = configuration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString(ConfigurationManager.AppSettings["ServiceBus.ConnectionString"]);
            transport.UseForwardingTopology();
            transport.Transactions(TransportTransactionMode.ReceiveOnly);
            var sanitization = transport.Sanitization();
            sanitization.UseStrategy<CustomSanitizer>();

            configuration.Conventions().DefiningEventsAs(type => type.Namespace.StartsWith("CurrencyVue.Domain.Events"));
            configuration.Pipeline.Register(new ContextBehaviour(), "Provides static access to current IMessageHandlerContext");

            return configuration;`

**Comment by danielmarbach** [comment] 2017-08-08 08:21
@mattdone01 Did you run without the debugger attached? When the debugger is attached for convenience reason [we always execute the installers](https://github.com/Particular/NServiceBus/blob/3f85a3df5b9e21af218c5eb9a59b41c41815387b/src/NServiceBus.Core/InitializableEndpoint.cs#L144)

**Comment by mattdone01** [comment] 2017-08-09 00:48
Yes I did. The problem I am trying to solve is the amount of time a debug console takes to load when there are a lot of event handlers (up to 2-3 minutes). Am I able to opt out of the "always execute the installers in debug mode convenience feature"? When you are start a debug console 10 times a day this gets to be an annoying time waste, almost to the point where we are looking at alternatives to NSB and ASB. Thanks.

**Comment by danielmarbach** [comment] 2017-08-09 13:35
@mattdone01 I raised [an issue in NServiceBus](https://github.com/Particular/NServiceBus/issues/4893). We will also investigate into why it takes so long.

**Comment by danielmarbach** [comment] 2017-08-09 14:52
With LOG DEBUG enabled, 30 handlers for 30 events and debugger attached

Start clean: 
 - 00:00:25.9581129
 - 00:00:25.0643197

Restart:
 - 00:01:13.3926295
 - 00:01:13.5702365

Quite insane you are right @mattdone01 

Will investigate more.

**Comment by danielmarbach** [comment] 2017-08-09 15:44
A preliminary first investigation shows that we can improve a lot here. 

- Topology section creation can be done concurrently
- Starting receivers in a Parallel.For is very expensive (as discussed months ago) and a synchronous blocking operation which actually does not need to be awaited

Will continue to investigate tomorrow and send in a few PRs as discussion points.

**Comment by danielmarbach** [comment] 2017-08-10 10:42
@mattdone01 

I raise the following issues

https://github.com/Particular/NServiceBus.AzureServiceBus/issues/597
https://github.com/Particular/NServiceBus/issues/4897

The core fix would already give you a really decent boost. I'm trying to get this in asap

**Comment by mattdone01** [comment] 2017-08-11 01:43
Thanks for all your help @danielmarbach. My team really appreciates it.

**Comment by danielmarbach** [comment] 2017-08-11 06:50
@mattdone01 I created a custom release build for you. It looks like the fix will take a few more days but the custom build should get you into a more decent situation regarding the startup behavior. Please try it out and see what it gives.
[ConcurrentSubscription.zip](https://github.com/Particular/NServiceBus.AzureServiceBus/files/1217104/ConcurrentSubscription.zip)

**Comment by mattdone01** [comment] 2017-08-14 03:42
Hi @danielmarbach , that patch makes start times considerably better now. We are down to about 15-20 seconds, which is pretty good. Thanks for your help on this. Let me know when it makes it in a GA release.

**Comment by janpieterz** [comment] 2017-08-17 09:10
@danielmarbach is this similar to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/522? If so, it sounds like we're about to cut our deployment times in half when this gets out 🙌

**Comment by danielmarbach** [comment] 2017-08-17 09:17
@janpieterz yes the root cause is what we have fixed. Feel free to use the above custom build and tell me what happens 👯‍♂️

**Comment by janpieterz** [comment] 2017-08-17 09:46
I'm on holiday so won't be able to for a while, but will mark this as to confirm, unless it'll be pushed into GA in the meantime.

**Comment by danielmarbach** [comment] 2017-08-18 12:45
6.4 is out which contains the fix https://groups.google.com/forum/#!topic/particularsoftware/fsNiiUJwwdc

Closing this.

**Closed by danielmarbach** 2017-08-18 12:45 UTC
Labels: State: Icebox

**Comment by danielmarbach** [comment] 2017-08-18 13:41
Btw. in 6.4 it is now possible to Disable the installers to run without manage permissions even with the debugger attached

**Comment by janpieterz** [comment] 2017-08-31 07:32
Great (startup and therefore deployment) speed improvement here! Thanks @danielmarbach

**Comment by danielmarbach** [comment] 2017-09-04 06:58
@janpieterz 🙇 thanks for giving feedback. Always appreciated!
