### ISSUE TITLE
Different error message for invalid queue/msg names

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.AzureServiceBus#228] opened 2016-05-12 14:56 UTC
Got this error today

>System.Exception: Invalid Rule name `GatedPublishRunner+Event` that cannot be used with Azure Service Bus. Rule name exceeds maximum allowed length or contains invalid characters. Check for invalid characters, shorten the name, or use `Sanitization().UseStrategy<ISanitizationStrategy>()` configuration extension.

Perhaps we can do something like this

>System.InvalidOperationException: Validation rule `[rulename]` triggered on `GatedPublishRunner+Event` which cannot be used with Azure Service Bus. Name contains invalid characters. Check for invalid characters or use `Sanitization().UseStrategy<ISanitizationStrategy>()` in configuration API.

1. `InvalidOperationException` instead of the root `Exception`
2. I was confused by "Invalid Rule name", @SeanFeldman suggested something like `entity`?
3. Two validations are performed and user now has to figure out what is actually going on.
4. "configuration extension" is mentioned, but I don't think end user should have to know it's using extension methods. Rather mention configuration API.

**Comment by SeanFeldman** [comment] 2016-05-12 23:50
Thank you @dvdstelt. This is good info.

:+1: 

#2 Rule name is invalid, not something within the name as @dvdstelt was trying to figure out. It would probably help to be specific that the rule entity name is problematic, to avoid confusion between rule name and rule itself.
#3 Spot on, will be changed in RC
#4 ""configuration extension" will be replace with "configuration API" to be also consistent with other exception messages the transport throws.

:-1: 

#1 `InvalidOperationException` instead of  `Exception` brings no value. There was nothing done incorrectly. There's a configuration that is needed. No need to introduce `InvalidOperationException` (or a custom exception as @ramonsmits suggested in slack). Users can't act upon this error in the code and continue execution.

**Comment by yvesgoeleven** [comment] 2016-05-31 14:27
Closing, duplicate of #230

**Comment by SeanFeldman** [comment] 2016-06-07 13:41
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/89ace2b4334e094acd8abba6e762161a4fa5a8ab

**Closed by SeanFeldman** 2016-06-07 13:41 UTC
Labels: Type: Refactoring
