### ISSUE TITLE
ASB V6 Wrong exception message on Clock Drift

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#343] opened 2016-09-23 08:15 UTC
As reported on the forums https://groups.google.com/forum/#!topic/particularsoftware/jw6CfDm48Gc, the exception "AzureServiceBusTopicSubscriptionManager can only be used in conjunction with windows azure servicebus, please configure the windows azure servicebus transport" is raised when the local clock is off by 30 seconds from the ASB server's clock. (V6 transport / V5 core)

NSB.ASB v6

Relates to https://github.com/Particular/NServiceBus.Azure/issues/309

**Comment by boblangley** [comment] 2016-09-27 19:14
The same issue was raised in https://eu1.salesforce.com/console#%2F500D000001GzoBo%23500D000001GzoBo_RelatedCommentsList_target also.

**Comment by yvesgoeleven** [comment] 2017-11-07 11:48
I don't see a way from preventing this issue

What happens:

Due to the clock drift and existing messages on the queue an exception is thrown during startup, this bubbles up (But should be logged afaik)
This causes the core to set up the default receiver (msmq) instead
Which does not cast to ASBDequeueStrategy and the null ref check causes
"AzureServiceBusTopicSubscriptionManager can only be used in conjunction with windows azure servicebus, please configure the windows azure servicebus transport" exception

The problem is specific to V6 transport, code has been replaced by TopologyOperator in v7

**Comment by danielmarbach** [comment] 2017-11-13 15:13
So a viable solution is to upgrade to v7 of the transport and then the problem is gone? If yes then I vote for closing this as won't fix for v6.

**Comment by SeanFeldman** [comment] 2017-11-15 15:25
Upgrading is the solution. Closing.

**Closed by SeanFeldman** 2017-11-15 15:25 UTC
Labels: State: Ready, Withdrawn
