### ISSUE TITLE
Support scaleout in different instance modes

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#124] opened 2016-02-22 11:16 UTC
The failure of test `When_publishing_to_scaled_out_subscribers_on_multicast_transports` highlighted a difference between core V5 / asb V6 & core V6 / asb V7 when it comes to scaleout and individualization behavior.

Core V5 & asb V6 supported modes
- all instances of an endpoint read from a shared queue & have a shared subscription for events
- or all instances have their own queue and their own subscription

Core V6 & asb V7 current modes
- all instances of an endpoint read from a shared queue & have a shared subscription for events
- or all instances have their own queue and their own subscription + a shared queue & subscription

This last mode is problematic for backward compat of standard topology & the common event distribution scenario to clear local cache in azure webroles, as it will duplicate events

We should have all 3 modes & allow user to configure which mode he wants to use

**Update**:

Proposed idea is to use endpoint name in conjunction with instance ID to achieve same result as was with data distribution mode. To confirm it works as expected, a POC is started (https://github.com/Particular/NServiceBus/issues/3638).

## Decision made

[The decision](https://github.com/Particular/NServiceBus/issues/3495) has been made to not solve the problem of data distribution at this point (NSB V6) and come back to it later, possibly in form of a backplane if needed. A workaround for Azure customers who want the described data distribution / cache invalidation feature to use an additional endpoint instance co-hosted with the primary one. The additional instance would have a name composed of a base endpoint name and some unique ID (RoleId for CS or Website_Instance_ID for websites). This will force the NSB routing to treat each of these as an independent logical endpoint (not instances of same endpoint) and events will be routed to each one. Example:

![image](https://cloud.githubusercontent.com/assets/1309622/20394342/61e2e7a2-ac9c-11e6-9710-288f2c0e5d71.png)

Where EP1 & EP2 should not include handlers for data distribution events to avoid subscription (possibly, by using message conventions to skip anything that is marked as data distribution event).

**Comment by SeanFeldman** [comment] 2016-02-22 23:58
Discussion about this issue in core: https://github.com/Particular/NServiceBus/issues/3495

**Comment by SeanFeldman** [comment] 2016-02-22 23:59
I have turned the test into `Explicit` for now to allow normal work w/o red for a test that can't be green.

**Comment by SzymonPobiega** [comment] 2016-03-17 04:49
@yvesgoeleven is this a duplicate of https://github.com/Particular/NServiceBus/issues/3406 ?

**Comment by SeanFeldman** [comment] 2016-03-31 14:07
@SzymonPobiega @yvesgoeleven could you please update this issue with the POC issue? Thanks :)

**Comment by SeanFeldman** [comment] 2016-03-31 18:42
Added _update_ section to the general description.

**Comment by yvesgoeleven** [comment] 2016-04-04 08:06
@SzymonPobiega is the data distribution scenario in scope for the work you're referring to?

**Comment by SzymonPobiega** [comment] 2016-04-05 06:13
My understanding is that data distribution via secondary endpoints POC is integral part of https://github.com/Particular/NServiceBus/issues/3406, that's why I asked about the possible duplicate.

**Comment by yvesgoeleven** [comment] 2016-04-05 08:03
@SzymonPobiega Ok didn't realize that, I've marked this as a duplicate then, and won't work on the item. I'll keep it open for now though, just as a mental reminder for myself to follow up with you. (I'm going to move my own attention towards doco)

**Comment by mikeminutillo** [comment] 2016-06-21 02:22
@SzymonPobiega @yvesgoeleven https://github.com/Particular/NServiceBus/issues/3406 was completed and https://github.com/Particular/NServiceBus/issues/3652 was raised and parked with the intention of making a change in a minor after the release of core v6. Does this issue need to be re-opened or can it be closed?

**Comment by yvesgoeleven** [comment] 2016-06-21 06:53
@mikeminutillo has the data distribution scenario been tested as part of this?

**Comment by mikeminutillo** [comment] 2016-06-22 01:26
@yvesgoeleven I do not know as I wasn't involved. @SzymonPobiega may know more.

**Comment by SzymonPobiega** [comment] 2016-06-22 06:30
@yvesgoeleven no. There was a decision (and I was not involved in it) to drop the data distribution PoC. We can make it a sample though.

**Comment by mikeminutillo** [comment] 2016-07-01 08:01
@yvesgoeleven @SzymonPobiega if there is work left to do, can it be raised in a new issue? This issue is labelled as Withdrawn and should be closed.

**Comment by SeanFeldman** [comment] 2016-11-17 15:07
This could be either documented as guidance or a sample.

**Comment by SeanFeldman** [comment] 2016-11-18 15:10
MSMQ example is already available: https://docs.particular.net/samples/routing/data-distribution/

**Comment by SeanFeldman** [comment] 2016-11-18 15:19
[Documentation](https://docs.particular.net/nservicebus/azure/data-distribution) is already in place pointing to the sample.

**Closed by SeanFeldman** 2016-11-18 15:19 UTC
