### ISSUE TITLE
Backport 'secure connectionstrings'

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#300] opened 2016-08-09 07:10 UTC
Investigate if the secure connectionstrings can be implemented somehow in the previous major, ~~so that SC can use it.~~

This will allows users to incrementally upgrade from v5 to v6

**UPDATE**

We can enable v6 of the transport to work with secured connection strings coming from endpoints using v7 transport. The change would require mapping registration similar to to v7. We would _only_ map from namespace names to connection string on the incoming messages. The benefits of doing so are:

1. Allow gradual upgrade (minor version upgrade for the older endpoints) w/o need for a massive NSB v6 upgrade.

**Comment by johnsimons** [comment] 2016-08-09 21:57
I would go to say that this needs to be done before the v7 release.
Without it the platform is broken!

**Comment by andreasohlund** [comment] 2016-08-17 07:43
Decription updated to reflect that SC isn't affected.


@Particular/azure-storage-queues-maintainers should a similar issue be raised for ASQ?

**Comment by SeanFeldman** [comment] 2016-08-17 14:58
Should we still consider this change (for asb 6.5.0)?

**Comment by SeanFeldman** [comment] 2016-08-17 18:59
@Particular/azure-service-bus-maintainers I suggest we move forward with this under maintainers budget.

**Comment by Scooletz** [comment] 2016-08-18 08:35
The secure connection strings feature, is it an opt-in as in ASQ? 
Should @Particular/azure-storage-queues-maintainers consider this as well then?

**Comment by SeanFeldman** [comment] 2016-08-18 23:57
@Scooletz it should be an opt-in for both, ASQ and ASB

**Comment by SeanFeldman** [comment] 2016-08-22 06:39
@Particular/azure-service-bus-maintainers Please have a look at [release-6.5 branch](https://github.com/Particular/NServiceBus.AzureServiceBus/tree/release-6.5). This should allow us to support messages with secured connection strings coming from endpoints using v7.

**Comment by SeanFeldman** [comment] 2016-08-22 06:42
We could release it along with v7 beta to allow customers to use it in their test drives.

**Comment by SeanFeldman** [comment] 2016-08-22 13:48
After talking to @yvesgoeleven about this, we've concluded that the expected behaviour on v7 transport for secure connection strings will be conceptually broken if v6 transport will be able to reply w/o securing connection strings. Therefore options are:

1. Instruct users to upgrade from upgrade from NSB v5 (transport v6) endpoints to NSB v6 (transport v7).
1. Release a new build of transport v5 that doesn't send **out** connection strings. Will required to release a major version. Since it's an upgrade to major, then option #1 will be equivalent. Therefore, do nothing other than #1.

@Particular/azure-service-bus-maintainers what are you thoughts? If first option is the most suitable, I will close the issue and remove release-6.5 as not needed.

**Closed** 2016-08-22 20:25 UTC
Labels: Size: S, Tag: Maintainer Prio, Type: Feature
