### ISSUE TITLE
DataBus headers are getting removed

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.AzureServiceBus#540] opened 2017-05-04 09:49 UTC
We send files via nservicebus & (azure)databus to azure service bus, but in some occasions it creates messages in asb and there are no databus-headers attached. I can't figure out why this is happening and the only clue I've got is our nservicebus logging file.

I've created a bug before in the databus repo [https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/22](url)

Can somebody take a look at our logging? First error on line 6829
[nsb_log_2017-05-02_0.txt](https://github.com/Particular/NServiceBus.AzureServiceBus/files/975723/nsb_log_2017-05-02_0.txt)

Thanx in advance

**Comment by yvesgoeleven** [comment] 2017-05-04 12:34
Those exceptions are internal to ASB, they are not uncommon to see these in the shared service (premium should not have this problem) and they should be resolved on their own. From the logs it appears to resolve itself. Is this the case? Or did you need to reboot before it continued processing?

Also, do you see any correlation between these exceptions and the missing headers?

**Comment by yvesgoeleven** [comment] 2017-05-04 12:37
PS: If you want more details on why the exception occurs, you have to submit the trackingid (TrackingId:425dfda8-5644-4316-be63-dc49e236c2fc) from the log to azure support. They can use this id to start an investigation to the cause.

**Comment by JSCProjects** [comment] 2017-05-04 13:01
@yvesgoeleven the amount of exceptions is equal to the amount of messages who have no databus headers. I will try to get the logging from the provided trackingid

**Comment by yvesgoeleven** [comment] 2017-05-04 13:52
@JSCProjects that is interesting. I will need to investigate but it could point to headers getting lost in the retry logic

**Comment by SeanFeldman** [comment] 2017-05-04 15:03
@JSCProjects would it be possible to provide a repro for this issue? Retry logic doesn't lose headers as @yvesgoeleven suspected, but it could be something else that is getting in the way. Thank you.

**Comment by JSCProjects** [comment] 2017-05-04 15:12
@seanfeldman the problem is that I don't know how to reproduce it. I really want to help you with that, therefore I asked the logging of azure from Microsoft

**Comment by SeanFeldman** [comment] 2017-05-04 15:16
@JSCProjects thank you, that could shed some light.
Troubleshooting this type of problems takes time. We'll have to play the elimination game 😃

**Comment by JSCProjects** [comment] 2017-05-08 07:25
Hi @SeanFeldman and @yvesgoeleven I've got a mail back from Microsoft and they saw some spikes and drops on their metric logs on a specific time. And that was the result of a guest OS upgrade on the tenant. They adviced me to implement an exponential backoff retry logic, but IMHO this is already implemented by nservicebus ;-)

**Comment by yvesgoeleven** [comment] 2017-05-08 07:29
@JSCProjects correct that is already in place.

**Comment by JSCProjects** [comment] 2017-05-08 08:11
@yvesgoeleven but how is it possible that when a message is retried by flr/slr the mandatory (databus) header is lost?

**Comment by yvesgoeleven** [comment] 2017-05-08 09:02
@JSCProjects I do not know yet. I verified the code and all headers and properties are copied over as far as I can see. Are there other headers lost or is it only the databus header? The transport does not treat it any differently.

**Comment by JSCProjects** [comment] 2017-05-08 09:21
afaik the only headers that were missing are those from the databus

**Comment by yvesgoeleven** [comment] 2017-05-08 13:00
I just tried to reproduce this by modifying the databus sample but couldn't. The header is still there after FLR, SLR and when moved to the error queue. This seems to work fine.

**Comment by yvesgoeleven** [comment] 2017-05-08 14:09
@JSCProjects in what version of the transport are you seeing this btw? I reproed using the latest

**Comment by SeanFeldman** [comment] 2017-05-08 14:51
Might need to get a repro to figure this out. Could be something else
getting in a way and causing this.

**Comment by JSCProjects** [comment] 2017-05-08 15:19
@yvesgoeleven wow you reproduced it? Really nice. I'm using the following packages

`  <package id="NServiceBus" version="6.1.3" targetFramework="net452" />
  <package id="NServiceBus.Autofac" version="6.0.1" targetFramework="net452" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.1.4" targetFramework="net452" />
  <package id="NServiceBus.DataBus.AzureBlobStorage" version="1.0.1" targetFramework="net452" />
  <package id="NServiceBus.Hosting.Azure" version="7.0.0" targetFramework="net452" />
  <package id="NServiceBus.Persistence.AzureStorage" version="1.0.0" targetFramework="net452" />`

I'm using particular tooling (ServiceInsight & ServicePulse).

**Comment by SeanFeldman** [comment] 2017-05-08 16:07
@yvesgoeleven moving to "In Progress" since you've managed to repro it.
Could you provide steps to repro or the link to a repro?

**Comment by yvesgoeleven** [comment] 2017-05-09 12:41
@seanfeldman @jscprojects Uhm, no I did not reproduce it...

>  just tried to reproduce this by modifying the databus sample but couldn't

**Comment by SeanFeldman** [comment] 2017-05-09 13:39
@JSCProjects looks like after all we do need a repro to solve the mystery. Is that an option?

**Comment by JSCProjects** [comment] 2017-05-09 13:45
I understand, but it’s almost impossible for me to reproduce it because it’s triggered by an guest OS upgrade from azure.

Met vriendelijke groeten / Kind regards,

Joey Chömpff

[http://www.jsc-projects.nl/userfiles/newlogo50percent.png]

JSC Projects
Blankena 16
8103 JC Raalte

Telefoon: 06-150 12 458
E-Mail: mail@jsc-projects.nl<mailto:mail@jsc-projects.nl>
Internet: http://www.jsc-projects.nl<http://www.jsc-projects.nl/>
Twitter: @JSCProjects<http://twitter.com/#!/jscprojects>
KvK te Zwolle: 08178187
BTW: NL105372055B01
Bankrekening: NL78 RABO 0110 2858 08

**Comment by SeanFeldman** [comment] 2017-05-09 16:57
@JSCProjects I'm not sure how to proceed from here as we can't repro this on our end.

> it’s triggered by an guest OS upgrade from azure

This is the part I'm having difficulty with. If guest OS upgrade kicks in, it would interrupt message dispatch, but not cause certain headers to be removed from messages.

**Comment by JSCProjects** [comment] 2017-05-09 17:05
@seanfeldman ok I understand. Perhaps Microsoft can shed some light. I'm also out of options. Don't know how  to rewrite endpoint.send(msg)

**Comment by SeanFeldman** [comment] 2017-05-09 17:08
@JSCProjects are there _any_ customizations related to databus? Trying to see if there's any direction we didn't evaluate.

**Comment by JSCProjects** [comment] 2017-05-09 17:16
@SeanFeldman if a propertyname ends with "LargePayload" then it's a databus property

**Comment by SeanFeldman** [comment] 2017-05-09 17:24
@JSCProjects I meant customizations that are not part of the standard NSB code. A custom behavior or such.

**Comment by JSCProjects** [comment] 2017-05-09 17:28
Nope nothing I try to keep it as clean as possible

**Comment by yvesgoeleven** [comment] 2017-05-10 19:06
@JSCProjects we are going to look into the path towards SC as well, it's another point where something could potentially be wrong (assuming the error happened after resubmit via Service Pulse?)

**Comment by SeanFeldman** [comment] 2017-05-10 20:31
@JSCProjects looking at this thread, can I suggest to get on a call with one of us (@yvesgoeleven or myself, based on your time and availability) to review this? There are way too many question marks and w/o deeper understanding or a repro would be hard to help. Thanks.

**Comment by JSCProjects** [comment] 2017-05-15 05:57
@SeanFeldman & @yvesgoeleven I've found in the deployment an older version of Microsoft.ServiceBus.dll (3.0.50700.7) I'm not sure this fixes it, but I'm gonna take a try.

**Comment by SeanFeldman** [comment] 2017-05-19 05:20
@JSCProjects any updates?

**Comment by JSCProjects** [comment] 2017-05-19 05:55
@SeanFeldman the last week we didn’t receive any errors, but I don’t know if there was guest os upgrade on azure


@JSCProjects<https://github.com/jscprojects> any updates?

**Comment by JSCProjects** [comment] 2017-05-19 14:24
@SeanFeldman Can you explain me what can go wrong here

`context.Send("queue-name", new Command()).ContinueWith(_ => {
       File.Move(file, "SOME-BACKUP_PATH");
       return true;
})`

The file is moved? But command isn't on the queue or audited. This is now happening instead of the missing header

**Comment by yvesgoeleven** [comment] 2017-05-19 14:36
@JSCProjects the 2 operations are completely disconnected and it may behave differently then it looks at frist sight.

Send doesn't really send, it adds to a list to be sent. After it is added to the list, you move the file. But if this takes long or an exception occurs or so then the send will not happen while your file has been moved.

Is the intention to move the file after the send happened?

**Comment by SeanFeldman** [comment] 2017-05-19 15:29
@JSCProjects what @yvesgoeleven said. You should really send a command to a handler that is responsible moving the file.

**Comment by yvesgoeleven** [comment] 2017-06-29 11:30
Closing this one as we can't reproduce it, feel free to reopen if needed.

**Closed by yvesgoeleven** 2017-06-29 11:30 UTC
Labels: State: Blocked
