### ISSUE TITLE
Startup speed is relatively slow

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.AzureServiceBus#522] opened 2017-04-07 14:29 UTC
Just converted endpoints from V5 to V6, and am noticing the startup speed being relatievly slow.
I'm using the new forwarding topology, and it seems like it takes a long time to add all those subscription rules (even when they're already there).

**Comment by SeanFeldman** [comment] 2017-04-09 04:53
@janpieterz could you please provide a bit more information?
- Stats comparison (v5 vs v6)
- What the topology looks like? 
- If possible to share some repro we can base of?

Please note [this issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/521), it could also reduce the bootstrapping time

**Comment by janpieterz** [comment] 2017-04-09 07:21
Sure!
Below ones are the same endpoint on the same hardware (production/staging). Differences would be V5 upgrade and move to NSB host instead of the Azure Cloud host.

V5:
```
09:08:44:321
09:09:08.577
24 seconds
```
V6
```
09:11:21:513
09:12:15:964
54 seconds
```

Topology is 6 endpoints, of which only two subscribe (this is one of those).

What I see in the logging is that these take up most of the time: https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L71. It does that for every subscription, 17 in this case. It runs on a small VM (1 core) which might limit the concurrency.
Could this behavior be joined on startup? Get all rules, compare to what it should be in memory, execute changes, instead of for each do a call? 

This is mostly limiting during deployments, where I see our deployment time shoot up in time and gain more than 3 minutes (bit more since deployment also takes up some resources)

Getting a repro shouldn't be too big a problem (and am assuming it will be comparable for any V5/V6 move with a decent amount of subscriptions) but am currently focused in shipping the V6 move here 😄

**Comment by SeanFeldman** [comment] 2017-04-09 10:11
> Could this behavior be joined on startup?

The current seam with NServiceBus core is to [receive a single subscription](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/fbe70f0a2d23947c61fa01283ead4c5467073ebf/src/Transport/Seam/SubscriptionManager.cs#L21) a time.  

> Get all rules, compare to what it should be in memory, execute changes, instead of for each do a call?

Unfortunately this is not an option due to ASB's API limitation. [Rules cannot be queries](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/fbe70f0a2d23947c61fa01283ead4c5467073ebf/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L80) and we have to try to create each rule to ensure that it is created or already exists (exception case). 

Management operations are all going through HTTP. Perhaps try to increase the [number of HTTP connections](https://docs.particular.net/nservicebus/azure-storage-queues/performance-tuning#network-optimizations) would help. 

1. What VM SKU are you using?
1. Just to confirm, 54 seconds is the time that it takes to start an endpoint with 17 subscriptions (endpoint subscribes to the 17 events)?

**Comment by janpieterz** [comment] 2017-04-09 10:14
Ah, that's a shame, might just be something we'll have to bite the bullet on then.

I'll try increasing the HTTP connections, see if it changes.

1. This runs on a group of A1's, which works fine for the day-to-day run.
2. 54 seconds is indeed for 1 endpoint with 17 subscriptions.

**Comment by SeanFeldman** [comment] 2017-04-10 17:59
We're planning bro change that in the future.
For now, could you please let me know if increasing max http connections helped or not. If it doesn't, I'll try to reproduce it (unless you have a simple repro to share).

**Comment by janpieterz** [comment] 2017-04-11 09:25
Just confirmed it, 2 different endpoints with 2 deployments before and after, no real difference. Keep in mind the A1's are single core machines so if there is a multi-threaded benefit, it won't be as significant here.

I've send you an endpoint to your email, showcasing the behaviour, filling out the config values with a servicebus. table storage and sql connection string should display.

**Comment by SeanFeldman** [comment] 2017-04-12 04:01
That might be it.
In v7 of the transport we [set the throttling](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e88d11c562e786fe188bc0ef163a8642c6fb305e/src/Transport/Seam/MessagePump.cs#L80) to the maximum concurrency of the endpoint. By default, it will be `max(2, num-of-logical-processors)`.

**Comment by janpieterz** [comment] 2017-04-12 06:40
Yeah, it probably isn't that high 😄 
We're changing our topology already to allow more cores per unit while maintaining two instances (hosting a web the services on the same VM, twice).

**Comment by SeanFeldman** [comment] 2017-04-17 17:08
@janpieterz what topology you're moving to? If you're using the Forwarding topology, you might be affected by [this issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/521).

**Comment by SeanFeldman** [comment] 2017-04-18 02:36
@janpieterz thanks for the repro. I've looked into it and these are the conclusions I have.

- V6 vs V7 of the ASB - with V6 `EndpointOrientedTopology` was the default and the only one. It created a subscription per event type with a single rule. Subscriptions could be queried. With V7 and `ForwardingTopology` there is a single subscription, but there's no way to query for the rules. Upon update, a rules has to be created and if already exists, an exception has to be swallowed. As a result of that, updating subscriptions is always slower than creating (see results below).
- Number of entities in the bundle (default is 2) - MSFT ASB documentation has indicated a limitation on number of connection per topic. To address it, the transport v7 has created 2 topics by default (`bundle-1` and `bundle-2`). This is unnecessary and will slow things down. (issue is raised but might be not so trivial to change the defaults).
- Debugger - if debugger is attached, execution time is significantly slower.

### bundles=2; debugger-attached=false;

**create (21 sec)**
2017-04-17 20:14:30
2017-04-17 20:14:51

**update (43 sec)**
2017-04-17 20:10:45
2017-04-17 20:12:28

### bundles=1; debugger-attached=false;

**create (15 sec)**
2017-04-17 20:17:58
2017-04-17 20:18:13

**update (23 sec)**
2017-04-17 20:19:20
2017-04-17 20:19:43

### bundles=2; debugger-attached=true;

**create (32 sec)**
2017-04-17 20:22:08
2017-04-17 20:22:40

**update (47 sec)**
2017-04-17 20:24:45
2017-04-17 20:25:32

My recommendation would be:
1. Decrease bundles to 1 (`transport.UseForwardingTopology().NumberOfEntitiesInBundle(1);`).
1. Measure time w/o debugger attached.
1. Keep an eye on issue https://github.com/Particular/NServiceBus.AzureServiceBus/issues/521

**Comment by janpieterz** [comment] 2017-04-18 05:42
Thanks a lot for the thorough investigation! Odd that MSFT does not open up that bit of the API, but that is obviously something to work around!

You're input is much appreciated, I'll decrease the bundle and keep an eye on the issue. Thanks.

**Comment by SeanFeldman** [comment] 2017-04-18 06:06
@janpieterz thank you for the pointer in the right direction. With this, I'm going to review how we update subscriptions and implement it using [`NamespaceManager.GetRulesAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.getrulesasync?view=azureservicebus-4.0.0)

**Comment by SeanFeldman** [comment] 2017-04-20 15:52
`NamespaceManager.GetRulesAsync()` with a `filter` options is broken at the ASB client level. 😞 

Alternative is to retrieve all the rules per subscriber and perform client-side evaluation. Given that endpoint event subscriptions are created one-by-one, it will mean fetching all the rules for each subscription. This could be less optimal than using the `filter`-ed option and not much different from what we do today in terms of performance. Saying that, it would be cleaner than `try`/`catch`-ing an exception.

In the future, hopefully we'll be able to switch to creating/updating subscriptions in a bulk upon startup and that would resolve this entirely. I've [raised a Core issue](https://github.com/Particular/NServiceBus/issues/4632) and until then it happens, will close this, replacing it with a [tracking new issue](#526).

**Closed by SeanFeldman** 2017-04-20 15:52 UTC
Labels: Refactoring, State: Backlog
