### ISSUE TITLE
NServiceBus stops dequeueing messages from Azure Service Bus queues

### ISSUE THREAD

**Issue by daerath** [Particular/NServiceBus.AzureServiceBus#531] opened 2017-04-26 20:53 UTC
We've seen this issue off and on for a while now (in both NSB 5 and NSB 6). I have some new information though to does narrow things down a bit (hopefully).

First, here are the versions of what should be the relevant nugets:

```
<package id="log4net" version="2.0.5" targetFramework="net452" />
<package id="Microsoft.Azure.Common" version="2.1.0" targetFramework="net461" />
<package id="Microsoft.Azure.Common.Dependencies" version="1.0.0" targetFramework="net452" />
<package id="NHibernate" version="4.1.1.4000" targetFramework="net461" />
<package id="NHibernate.SqlAzure" version="2.1.5" targetFramework="net461" />
<package id="NServiceBus" version="6.1.4" targetFramework="net461" />
<package id="NServiceBus.Autofac" version="6.0.1" targetFramework="net461" />
<package id="NServiceBus.Azure" version="7.0.0" targetFramework="net461" />
<package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.2.0" targetFramework="net461" />
<package id="NServiceBus.DataBus.AzureBlobStorage" version="1.1.0" targetFramework="net461" />
<package id="NServiceBus.Hosting.Azure" version="7.1.2" targetFramework="net461" />
<package id="NServiceBus.Hosting.Azure.HostProcess" version="7.1.2" targetFramework="net461" />
<package id="NServiceBus.Log4Net" version="2.0.0" targetFramework="net461" />
<package id="NServiceBus.NHibernate" version="7.1.4" targetFramework="net461" />
<package id="NServiceBus.Persistence.AzureStorage" version="1.2.0" targetFramework="net461" />
<package id="WindowsAzure.ServiceBus" version="4.0.0" targetFramework="net461" />
<package id="WindowsAzure.Storage" version="8.1.1" targetFramework="net461" />
```

Ok, the behavior is this. We have cloud services that send and receive messages via Azure Service Bus. Then, without us changing anything (no source code changes, nothing in the cloud config, etc.) the waworkerhost.exe process will drop to 0% CPU and stay there indefinitely. There are no error messages. Nothing in the event log. I’ve tried looking in dbgview to see if anything jumps out at me and nothing did (although there was a lot of noise in there. Cloud services chat up the diagnostic trace log it seems). I also tried using procdump to display first chance exceptions and didn’t see anything there either. I don’t have a tracking ID or anything I could use to generate a support ticket.

There is an underlying component to this in Azure because it hits all instances of the same service nearly simultaneously. Whatever is happening isn’t being handled within NServiceBus and processing halts. From what we’ve seen, it never comes back. The only “fix” we've found so far is to have an external process that watches queue sizes and measures CPU use on waworkerhost.exe. If it detects the problem it will kill waworkerhost.exe. Azure restarts it and we continue. This repeats, typically for a few days, when the problem goes away as mysteriously as it appeared. This works, but it is far from ideal.

I was chatting with Sean Feldman about an unrelated issue and he directed me to a page detailing Critical Error Behavior. I took the code from that page and modified one of our services in test and deployed it.

The same problem happened and the critical error behavior did not activate. Nothing was logged. It sat at 0% CPU.

Until today this only hit one service out of a dozen. That service uses sagas, timeouts, and azure service bus deduplication, so we weren’t 100% sure if this issue was with SQL Azure, or the bus, or was somehow related to timeouts. However, it seemed like it was a bus issue because we stopped dequeueing. Today I saw the same problem hit a different service. That one is pretty simple. It processes messages and calls a Web API. No sagas. No dedup. No SQL Azure. The only common theme between the two is the service bus.

I managed to get a couple of screenshots of the service bus performance counters and this is what I see after it happens. Unfortunately I didn’t get a screenshot of the exact moment it occurred, but that one showed processing and then suddenly all trace lines dropped to 0. Then it appears to start back up, it may process a message or two, and then it stops again.

I have a feeling that this is related, in some way, to load, but that’s purely a guess. The system runs through tens of millions of messages a day. The two services that have manifested this behavior are involved in almost every message and we’re running 4 – 6 instances of those. The other services are far lower load (and typically 2 instances) and have not manifested this problem.

This is a screenshot of perf counters after it had stopped. The line that spiked is ReceiveMessageLatency.
![stops](https://cloud.githubusercontent.com/assets/3658944/25456367/bbad0862-2aa0-11e7-9943-f7094ebfe465.png)

This screenshot is after the first one. We go completely dead, then it looks like it tries to come back, but doesn't go anywhere. Then there are more ReceiveMessage Latency spikes and then it goes back down to 0 again.
![doesthisafteritstops](https://cloud.githubusercontent.com/assets/3658944/25456363/b5b5ed70-2aa0-11e7-9d31-b6126752b339.png)

I'm at a loss here. I don't know how to investigate this. That I can't even get an error message of some kind makes this even more confusing.

**Comment by SeanFeldman** [comment] 2017-04-26 23:11
@daerath there's a reference to the Azure DataBus. Do both services that demonstrate this behavior use azure databus?

**Comment by SeanFeldman** [comment] 2017-04-26 23:40
Next time you see this freeze, could you take a memory dump and share with us?

**Comment by daerath** [comment] 2017-04-27 11:14
Both services do use database, however we implemented a feature in our base command that will put the entire command in Azure Service Bus if it doesn't exceed the command size limit.  Basically, there are two Argument properties.  One that is linked to DataBus and another that is not.  The one linked to the databus will return null if the message will fit onto the bus with all of its arguments.  If it won't fit, it returns the list of arguments which are then routed to blob storage.  For the test messages I'm running right now it will never actually store messages in blob storage because the contents are too small.

**Comment by daerath** [comment] 2017-04-27 11:19
I was able to open a case with MSFT on this as well and sent in the timestamps when I saw a number of "freeze" issues.  They responded back that during the period of time of one of them they saw a number of timeouts:

• sends and receives occur normally until...
• 19:35:56 timeout followed by entity abort and reload
• 19:36:18 sends and receives resume and continue normally until...
• 19:38:18 timeout followed by entity abort, but the reload does not go smoothly and operations continue to timeout until...
• 19:40:13 sends and receives resume and continue normally thereafter

The "sends and receives resume and continue normally" parts are when we killed worker host and it restarted.  The engineer asked if we changed the retry settings in the client.  I'm thinking this isn't so much about message level retries and is perhaps more connection level?  I sent in some follow-up questions to try and clarify, but I wanted to mention it here in case there is customization of retry logic, or somewhere that you may be explicitly handling timeouts?

I'm going to try and get an event trace, but it seems I'm having issues installing the event definitions.  I'd thought they would install when the performance counters were installed, but that doesn't seem to be the case for some reason.

**Comment by yvesgoeleven** [comment] 2017-04-28 09:26
@daerath we are aware of an issue with the databus that can cause behavior like this over time, can you first validate that the following is not true: 

If messages with databus entities have no time to live specified the entities will be stored in blob storage until the end of time. The databus cleanup mechanism needs to query all the blobs before it can see which are expired. But as no TTL is specified, none will be cleaned. While entities pile up over time, this causes the clean up query to slow down, resulting in overlapping queries eventually. Each query takes up a tcp connection, ultimately resulting in no more tcp connections for ASB.

It takes up a significant amount of time to get in this state, usually a few years, but we've seen it before.

Can you check how many databus entities there are in your storage account?

**Comment by daerath** [comment] 2017-04-28 14:56
@yvesgoeleven Our current storage in databus is 2186 files totaling 3.99GB.  However, in my test environment I had 200 blobs or so (tops) because my test messages almost entirely fit into memory.  I didn’t make note of the total size before I cleared that one, but I can’t believe it would be close to the size in production.  I queried the account with Azure Storage Explorer.  Those counts should be accurate unless there is a type of blob that Azure Storage Explorer doesn’t display.

Sometime last June it used to be orders of magnitude larger.  It was big enough that we had to run out-of-band processes to clear out blobs that would never expire.  That’s why I implemented the code to put the whole message in Azure Service Bus if it would fit and to only use the databus if it was too large. *

The storage now clears out every 14 days like clockwork.  Just to confirm I checked and the last blob in there is 4/14.

That does bring up a question though.  Could the total size of that storage account be an issue?  Do those queries need to pull back the whole blob to get the data needed to see if it should delete a blob, or is this only an issue in the scenario where you have millions of blobs?  Looking at one I use for testing, it’s showing as a Standard storage account.  I’m not sure that should matter, but thought I’d include that information.

I’m going to try and stand up a repro with simpler code to see if I can pinpoint this and I’m also going to gradually scale up load testing on the main solution to see if there’s a tipping point.

* Related, but we got a pretty insane performance boost from dynamically using databus or putting it in azure service bus based on some performance testing.  That’s a feature you could add to make DataBus more intelligent (and it would potentially let us remove that bit of custom code!)  =)  I’d be happy to share the implementation although you could do it much cleaner by adding it directly to the databus feature (we’re doing it in the command itself).  Related, we also added one for stupidly gigantic data to lazy load it from blob storage, but that’s not in use for the current system.

**Comment by SeanFeldman** [comment] 2017-04-28 15:20
@daerath databus has a [design issue](https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/14) you could subscribe to. If messages do not have [TTBR](https://docs.particular.net/nservicebus/messaging/discard-old-messages) defined, blobs will remain in the storage and you'd have to clean them up just like you've described. When you scale your endpoints, current implementation causes each instance to query for blobs to retrieve their data to find out on the client side what blobs to remove. That's why we think it could be related.

> Could the total size of that storage account be an issue?

Not the storage account as a whole, but the size of attachments container definitely yes.

In regards to stream approach, we've got a [stream based sample](https://docs.particular.net/samples/pipeline/stream-properties/). All improvements/suggestions for DataBus are welcomed. You can raise them as issues in https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/ repo.

**Comment by daerath** [comment] 2017-04-28 16:42
We're not running our out of band cleanup tool any longer.  The cleanup is being done by NServiceBus at this point.  We have one command with an explicit TTBR (set to 4min, coincidentally generated by the service that seems to freeze randomly).  None of the other commands have TTBR set.

Now that I think about it.  That command will almost always (if not always) be small enough to not get a blob created in blob storage because of the dynamic logic I mentioned earlier.  It'll travel entirely over the service bus, arguments and all.

What we opted for instead of TTBR on every command is to set a DefaultTTL of 14 days when we configure the Azure Data Bus.  That way we get cleanup on all blobs that are big enough to go into the database (and not with the command itself on the bus)

`configuration.UseDataBus<AzureDataBus>()
.ConnectionString(databusConnectionString)
       .DefaultTTL(Convert.ToInt64(TimeSpan.FromDays(14).TotalSeconds)); `

We could probably knock that down to 7 to reduce overall size.  I suppose we could look at removing the default TTL and put TTBR on all commands although some of them would likely be set to a few days while others might only be a few minutes.  Does running mixed mode (some with TTBR and some without and a default TTL to book-end cleanup) have potential performance issues?

In case it is also relevant, we're not using the default DataBusProperty and are instead defining one explicitly (argumentsasencryptedstring - which is basically a list of arguments that we serialize to json and encrypt)

How often do the services check for blobs?  What about the possible impact of contention on the databus storage account if there are 30 odd services running all pointing at that blob storage account?  Is there a way to tell some services to not try and delete from blob storage?  We’re not in the category of having years’ worth of data stored.  Unless this is due to something like too many services trying to query and delete then I don’t know if this is the underlying cause.  That this focuses on a single service is also peculiar

That aside, I'll give the design issue you linked a read through to see if anything jumps out at me.  I'll also mention the stream based approach to the team.  That's the first time I've seen it.  What's the level of complexity to implement something like that?  If there is a chance that our issues stem from using databus then I’m interested in seeing how that could be the cause.  How does it perform by comparison to DataBus for contents from a few K upwards to multi-MB?  The upside is that it could let us remove our “put on bus, put in storage” decision tree and I’m all for pulling out code like that if I can get away with it.  =)

**Comment by daerath** [comment] 2017-04-28 17:11
One minor update.  Adding this here in case someone is responding to my rather long message above.  =)

Why would only one service show this behavior and none of the others?  For me that's the real "WTF!???" part of this.  I have seen it one time (in the last year) on another service, but once and only once.  That happened two days ago but I'm not sure that was the same cause (it could have been, but honestly I'm not sure.

**Comment by daerath** [comment] 2017-05-01 22:53
@SeanFeldman Ah, sorry about confusing the other thread (the one about duplicates).  I meant, I am starting a scale-up approach to try and repro this issue with our code and a non-customized NSB version to try and pinpoint the issue.  It *does* appear to be related to load.  Part of this test is going to have a version with DataBus and one without.

**Comment by yvesgoeleven** [comment] 2017-05-02 09:19
> Would this behavior also cause an almost instant re-freeze though? 

No the databus issue would definitly not show immediately, it takes a lot of time before it occurs. If the cleanup is scheduled every minute and each cleanup would take infinite time (and the overlap fix is not applied) then it would still take 64000 minutes to exhaust all tcp connections...

**Comment by daerath** [comment] 2017-05-04 17:09
@SeanFeldman I will try and share a memory dump.  I'm currently attempting to repro this with standalone code.  I'll keep you updated on this as I learn (hopefully) more.

**Comment by SeanFeldman** [comment] 2017-05-19 05:21
@daerath any updates?

**Comment by daerath** [comment] 2017-05-23 18:04
Hey, was on vacation.  We haven’t been able to repro it again, so we’re basically stuck waiting to see if/when it happens again.

I may have some additional time over the next two weeks to see if I can make a repro that can trigger this condition.

I will say though, the other person who reported this issue a week or two ago seems to have the same error behavior.  Works until it doesn’t, only when load is high, plus they’re also using nhibernatepersistence (which may or may not be related).  There may be a way we can add app insights into the mix to try and gain some visibility, we’re looking into that as well.

=/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yvesgoeleven** [comment] 2017-06-29 11:31
Closing as we cannot reproduce this, feel free to reopen if it occurs again

**Closed by yvesgoeleven** 2017-06-29 11:31 UTC
Labels: State: Blocked
