### ISSUE TITLE
The given key (AzureServiceBus.Serialization.BrokeredMessageBodyType) was not present in the dictionary.

### ISSUE THREAD

**Issue by ottarhenanger** [Particular/NServiceBus.AzureServiceBus#478] opened 2017-01-20 10:36 UTC
The exception below suddenly appeared for in our test environment:

The given key (AzureServiceBus.Serialization.BrokeredMessageBodyType) was not present in the dictionary.

Stack-trace is below:

`System.Collections.Generic.KeyNotFoundException:
   at NServiceBus.Settings.SettingsHolder.Get (NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs: 94)
   at NServiceBus.Settings.SettingsHolder.Get (NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs: 20)
   at NServiceBus.Transport.AzureServiceBus.DefaultBatchedOperationsToBrokeredMessagesConverter.CreateBrokeredMessage (NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultBatchedOperationsToBrokeredMessagesConverter.cs: 183)
   at NServiceBus.Transport.AzureServiceBus.DefaultBatchedOperationsToBrokeredMessagesConverter.Convert (NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultBatchedOperationsToBrokeredMessagesConverter.cs: 29)
   at System.Linq.Enumerable+WhereSelectListIterator`2.MoveNext (System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Collections.Generic.List`1..ctor (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Linq.Enumerable.ToList (System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.RouteBatch (NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs: 79)
   at NServiceBus.Transport.AzureServiceBus.DefaultOutgoingBatchRouter.RouteBatches (NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\DefaultOutgoingBatchRouter.cs: 42)
   at NServiceBus.Transport.AzureServiceBus.Dispatcher.Dispatch (NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Seam\Dispatcher.cs: 36)
   at NServiceBus.RoutingToDispatchConnector.Invoke (NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Outgoing\RoutingToDispatchConnector.cs: 49)
   at NServiceBus.SerializeMessageConnector+<Invoke>d__1.MoveNext (NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Outgoing\SerializeMessageConnector.cs: 39)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at NServiceBus.UnicastSendRouterConnector+<Invoke>d__2.MoveNext (NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\Routers\UnicastSendRouterConnector.cs: 79)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Telenor.External.Api.Controllers.SubscriptionController+<SetLicenseTotalAsync>d__18.MoveNext (Telenor.External.Api, Version=1.0.16363.1, Culture=neutral, PublicKeyToken=null: C:\a\1\s\src\Telenor.External.Api\Controllers\SubscriptionController.cs: 179)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__3`1.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__0.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__5.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__0.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__2.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Controllers.AuthenticationFilterResult+<ExecuteAsync>d__0.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext (System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
`

**Comment by yvesgoeleven** [comment] 2017-01-20 12:52
@ottarhenanger Can you elaborate on the word 'Suddenly' what changed that could cause the key not to be there? The transport always sets a default for this setting, https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Config/DefaultConfigurationValues.cs#L39, so I wonder what could have been the cause of it's removal. Do you have a repro of this issues that we could use to investigate the issue?

**Comment by ottarhenanger** [comment] 2017-01-20 13:30
@yvesgoeleven The error occurred only for 2 requests issued by our Web API on our QA environment. The system has been running for over a month without changes, suddenly these requests failed. I've tried to recreate the problem on my local PC to see if it was related to some content, but not able to recreate. The only indication is the stack trace captured by AppInsight and a HTTP 500 returned by our Web API controller.

The code in our Web API controller (send-only endpoint) is as following:

   public async Task<IHttpActionResult> CreateAsync([ClientTransaction] string transactionId, [Required] Subscription subscription)
        {
            // Generate a new service task
            var taskOrder = await TaskService.NewTaskAsync(ApiResources.Subscription, ApiResources.SubscriptionActions.Create, ResellerId, transactionId);

            // Publish process new subscription to service bus
            await ServiceEndpoint.Send(new ProcessCreateSubscription
            {
                TaskId = taskOrder.TaskId,
                ResellerId = ResellerId,
                Subscription = Mapper.Map<Subscription, InternalModel.Subscription>(subscription)
            });

            return Ok(Mapper.Map<TaskOrder>(taskOrder));
        }

Our system is hosted by Azure Service Fabric and the following dependencies exists:

 <package id="NServiceBus" version="6.1.1" targetFramework="net461" />
  <package id="NServiceBus.Autofac" version="6.0.1" targetFramework="net461" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.1.0" targetFramework="net461" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureStorageQueues" version="7.0.0" targetFramework="net461" />
  <package id="NServiceBus.Persistence.AzureStorage" version="1.0.0" targetFramework="net461" />
  <package id="NServiceBus.Serilog" version="3.0.1" targetFramework="net461" />

**Comment by yvesgoeleven** [comment] 2017-01-20 13:43
Thanks for the info. Anything special in the endpoint configuration that I need to be aware of?

PS: why are you including both ASB & ASQ transports? Are you using both in the same appdomain?

**Comment by ottarhenanger** [comment] 2017-01-20 13:49
Actual transport is selected based on config during startup, so both binaries are included. In prod and QA, ASB is used. Locally on deg PC, ASQ is used.

**Comment by yvesgoeleven** [comment] 2017-01-20 14:08
@ottarhenanger is that done to allow devs to use local emulator? Or is there another reason to switch transports?

**Comment by SeanFeldman** [comment] 2017-01-20 14:59
@ottarhenanger when you tried to repro this locally, where you using ASQ or ASB? Thank you.

**Comment by SeanFeldman** [comment] 2017-01-24 23:31
@ottarhenanger can you repro this issue?
We really need some sort of repro to help with this.

Side note - I suggest to use the same transport across the board and not to switch.

**Comment by Scooletz** [comment] 2017-02-13 15:28
Closing for now. Please reopen if you can reproduce the issue.

**Comment by santo2** [comment] 2018-01-19 12:20
Hi I'm having the same issues right now. Did anyone find a solution for this please?

**Comment by yvesgoeleven** [comment] 2018-01-19 12:30
@santo2 no, we haven't seen it again. As it is happening for you, would it be possible to share a reproduction?

**Comment by santo2** [comment] 2018-01-19 13:06
Hi Yves, thanks for your reply. I will try to make a separate solution asap. Probably not today!
We are now testing one code change: in the code, the endpoint instance was created each time again instead of having a singleton. this exception was not happening completely from the beginning on deployment, but after some time, after adding some messages, tweaking some data.

**Comment by SeanFeldman** [comment] 2018-01-22 16:27
> Could having multiple instances give any issues in the SettingsHolder which you can find back in the stacktrace of Ottar?

Really depends how those instances were created. That's why seeing a repro would help so much @santo2

**Comment by yvesgoeleven** [comment] 2018-01-23 12:15
I think I understand what is happening.

Stopping an endpointinstance clears the settingsholder, https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L54

But the endpointinstance Send/Publishes/Subscribe methods can still be invoked, https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L76, it doesn't warn that the endpoint is stopped

So this would result in runtime exceptions such as missing keys.

I raised an issue to provide a better exception.

**Comment by SeanFeldman** [comment] 2018-06-15 15:34
> I raised an issue to provide a better exception.

@yvesgoeleven could you please link that sentence to the issue you've raised to help those that find this issue navigate to the right one. Thanks.

**Closed by SeanFeldman** 2018-06-15 15:34 UTC
