### ISSUE TITLE
Infinitest went down on the following exception, figure out why

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#273] opened 2016-07-01 12:31 UTC
2016-07-01 12:29:32.820 WARN  NServiceBus.AzureServiceBus.Utils.MessageReceiverExtensions A timeout exception occured while trying to complete a batch of messages, the exception was The request operation did not complete within the allotted timeout of 00:01:06.4501013. The time allotted to this operation may have been a portion of a longer timeout. TrackingId:b4922b69-136d-4567-9fb1-6dce7d6bdc12, Timestamp:7/1/2016 12:29:32 PM
System.TimeoutException: The request operation did not complete within the allotted timeout of 00:01:06.4501013. The time allotted to this operation may have been a portion of a longer timeout. TrackingId:b4922b69-136d-4567-9fb1-6dce7d6bdc12, Timestamp:7/1/2016 12:29:32 PM

Server stack trace: 

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<GetAsyncSteps>b__35(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndUpdateCommand(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.<.ctor>b__1(IAsyncResult result, Boolean forceCleanUp)
   at Microsoft.ServiceBus.Messaging.BatchManager`1.PerformFlushAsyncResult.OnFlushCompleted(IAsyncResult result, IList`1 batchedObjectsAsyncResults)

Exception rethrown at [5]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.BatchManager`1.EndFlush(IAsyncResult result)

Exception rethrown at [6]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.BatchManager`1.EndBatchedOperation(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.BatchManagerAsyncResult`1.OnBatchedCallback(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [7]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.OnEndComplete(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryMessagesOperationAsyncResult.<GetAsyncSteps>b__8d(RetryMessagesOperationAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [8]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndCompleteBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AzureServiceBus.Utils.MessageReceiverExtensions.<SafeCompleteBatchAsync>d__1.MoveNext() in C:\Build\src\Transport\Utils\MessageReceiverExtensions.cs:line 18

**Comment by yvesgoeleven** [comment] 2016-07-01 12:38
Note, this is not the cause of the process going down, but a symptom

**Comment by SeanFeldman** [comment] 2016-07-02 05:53
@yvesgoeleven this exception should have been caught and swallowed [according to the code](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/ae2178d1f514a7919c537afa264932228e44ea51/src/Transport/Utils/MessageReceiverExtensions.cs#L42). Looks like this is critical enough that it bubbles up anyways?

**Comment by yvesgoeleven** [comment] 2016-07-05 12:11
@SeanFeldman I think the TimeoutException that takes down the process is not this TimeoutException but another one somewhere. I added unhandled exception & task tracing at appdomain level to hopefully figure out where it comes from when it happens again.

**Comment by abombss** [comment] 2016-07-10 14:45
We get these all the time, would love to see what you uncover, we have yet to get a good diagnostic.

**Comment by SeanFeldman** [comment] 2016-09-19 05:30
@yvesgoeleven how's Infinitest doing?

**Comment by SeanFeldman** [comment] 2016-11-25 15:53
@yvesgoeleven what do we do with this one?
If we can't repro or find out what happened, there's no point of having this one in the backlog.

**Comment by yvesgoeleven** [comment] 2016-11-26 21:22
@SeanFeldman keep it open, eventually we'll get more details about the cause and figure it out #nevergiveup

**Comment by janpieterz** [comment] 2017-02-11 06:44
We have encountered these this morning (and I think previously too). A couple of things I noticed:

- We are running two environments  (same Azure region but totally separate) and it occurred within around 3 minutes of each other on both environment, (maybe there was more something going wrong with ASB that NSB didn't handle very well more than anything else)
- Running V5 of NSB (and the other dependencies of Azure etc that belong to it), so not the async version for this product (yet)
- It was in our case done by scheduled messages not being able to be sent. We send these every minute (heartbeat), but of the 6 endpoints on each environment it only affected two (different endpoints, different environment)
- The scheduled messages in both cases were never re-scheduled again, which was in the end the only effect of this, the endpoints seem to actually keep running

Stack trace:
```
System.TimeoutException: The request operation did not complete within the allotted timeout of 00:01:10. The time allotted to this operation may have been a portion of a longer timeout. TrackingId:a110fdac-8599-4186-b1d5-eca533225978, Timestamp:2/11/2017 5:09:25 AM

Server stack trace: 


Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.DuplexCorrelationAsyncResult.End(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpTransactionalAsyncResult`1.<GetAsyncSteps>b__35(TIteratorAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.EndSendCommand(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndSend(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [5]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.RunSynchronously()
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueSender.Send(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusQueueSender.cs:line 41
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.SendInternal(TransportMessage message, ISendBrokeredMessages sender, SendOptions options, Boolean expectDelay) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 57
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.<>c__DisplayClass6_0.<SendInternal>b__0() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 45
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.SendResourceManager.Commit(Enlistment enlistment) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\SendResourceManager.cs:line 25
```

This was preceded by:

![image](https://cloud.githubusercontent.com/assets/383634/22851804/8ef076d6-f02d-11e6-9a1b-225ac5b49e6a.png)

Hope this sheds some more light on the issue @yvesgoeleven and @SeanFeldman , certainly not the most pleasant way of waking on on a Saturday morning! 😄 ☕️

**Comment by janpieterz** [comment] 2017-02-11 09:54
To add to that, this screenshot might show more (these are all the warnings, errors and fatals logged by NSB during the period).

You see that the endpoints that went down (Staging ITops.SMS and Production Gateway are the ones logging the most (the other endpoints send their heartbeats too, which is interesting), and it's only ITops.Email that has it once, (4th and 5th from bottom) but a different exception.

![image](https://cloud.githubusercontent.com/assets/383634/22852962/7c860180-f048-11e6-9339-127b20e7d99d.png)

**Comment by abombss** [comment] 2017-02-11 15:21
Based on the tracking ID you sent from the timeout the requests actually
never hit the server. We get these pretty regularly, I say regularly as in
a fraction of a percent of total traffic but we see some everyday.
Microsoft has been pretty unhelpful on these and we have no good ideas.

My assumption it's an issue with the ASB gateway of some kind. I can say
that over time, last 2 years the problem has gone down and whether it's
upgrades in the ASB client or their server something has gotten better but
certainly not eliminated.

The problems are so infrequent and without MS being able to provide any
diagnostics on their end its nearly impossible to trace or diagnose and
correlate to anything on our side. The ASB 3.x client seems like it made
the biggest difference.

We are going to upgrade to premium at some point and I wonder if that might
fix the issue. It could potentially be a noisy neighbor problem with other
namespaces running on the gateway you are connected to.

I know for a fact it's not an issue with NSB, we see the problem even on
our endpoints that don't use NSB. However, it should be handled gracefully
in NSB since it's a known transient issue.

**Comment by janpieterz** [comment] 2017-02-11 15:28
That is some great info, at least for me, @abombss, cheers.

It would be great if it could be handled gracefully, certainly because apparently the scheduling fails if 1 message does not get sent, which seems like a pretty serious defect.

**Comment by SeanFeldman** [comment] 2017-02-11 15:29
Jan-Pieter,

You can take the TrackingID and provide it to MSFT support to investigate
and provide you a reason for these.

**Comment by janpieterz** [comment] 2017-02-11 15:34
Thanks, I've asked them to look into it. Regardless though, it seems like not sending one message has a lot of effects that I wouldn't reasonably expect, with partial outage and a crucial feature (scheduling) essentially stopping, just for whatever reason that one message threw those errors. 

Should I open another issue to look into that?

**Comment by SeanFeldman** [comment] 2017-02-13 14:58
I'm not sure if a separate issue would help. The fact that it was a scheduled message or not doesn't really make a difference. If broker can't handle the message (as in this case), it won't differentiate between messages. Ideally, being able to reproduce this issue would be the best. But we can't force ASB gateway to fail.

**Comment by janpieterz** [comment] 2017-02-13 16:10
Isn't it a bit more serious than just one message failing since it brings down the scheduler, and this schedule never fires again?

**Comment by SeanFeldman** [comment] 2017-02-13 16:54
@janpieterz is that a custom scheduler you're referring to?
Could you elaborate on how it's implemented and operating?

**Comment by janpieterz** [comment] 2017-02-13 16:59
No custom, NServiceBus built in scheduler. See below code, literal copy of what stopped after above exceptions.
Obviously the heartbeat isn't that big a deal (though our monitoring wasn't happy 😄 ), but there are other schedules that would be more troublesome.

``` c#
public class StartStopMessages : IWantToRunWhenBusStartsAndStops
{
	private static readonly ILog Log = LogManager.GetLogger<StartStopMessages>();
	public Schedule Scheduler { get; set; }
	private readonly string _environment = CloudConfigurationManager.GetSetting("LoggingEnvironment");
	public void Start()
	{
		Scheduler.Every(TimeSpan.FromMinutes(1), "Heartbeat", delegate
		{
			Log.DebugFormat("{Env} Heartbeat from {End}", _environment, EndpointConfig.EndpointName);
		});
		Log.Info("{Environment} Endpoint starting");
	}

	public void Stop()
	{
		Log.Info("Endpoint stopping");
	}
}
```

**Comment by SeanFeldman** [comment] 2017-02-13 17:11
@janpieterz I see. I would not recommend this scheduler API to be used if you scale out your endpoints, but in your case you **do** want to execute logs on each endpoint. 
Let me dig into this a bit more. Meanwhile, have a look at [monitoring and heartbeats](https://docs.particular.net/servicepulse/intro-endpoints-heartbeats) using ServiceControl.

**Comment by SeanFeldman** [comment] 2017-02-13 21:22
@janpieterz I have looked into [Scheduler API](https://docs.particular.net/nservicebus/scheduling/) and it states the following:

>  The scheduling infrastructure leverages the approach of reliable messaging with the NServiceBus core functionality. This allows scheduling to include features such as built in retries and forwarding to the error queue.

This means that NSB will reschedule every given interval (in your case 1min) a [ScheduledTask message](https://github.com/Particular/NServiceBus/blob/530706d3189a948a9dd55df65e3f073c775ecda6/src/NServiceBus.Core/Scheduling/ScheduledTaskMessageHandler.cs#L14) to re-run your delegate. If ASB gateway is erroring, the message will be retried as defined by the ASB transport settings. In case ASB gateway is misbehaving (down or has an outage) and all retries were exhausted, the message will be sent to an error queue and re-scheduling won't happen.

If the objective of your scheduled task is to report that the endpiont is up and running, then you could do the following:

```c#
public class StartStopMessages : IWantToRunWhenBusStartsAndStops
{
    private static readonly ILog Log = LogManager.GetLogger<StartStopMessages>();
    private string _environment = "repro";
    private CancellationTokenSource cts = new CancellationTokenSource();
    private Task scheduledTask;

    public void Start()
    {
        scheduledTask = Task.Run(async () =>
        {
            while (!cts.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(20), cts.Token).ConfigureAwait(false);
                Log.DebugFormat("{0} Heartbeat from {1}", _environment, "Samples.Azure.ServiceBus.Endpoint1");
            }
        }, cts.Token);

        Log.Info(_environment + " Endpoint starting");
    }

    public void Stop()
    {
        Log.Info(_environment + " Endpoint stopping");

        cts.Cancel();
        scheduledTask.Dispose();
        cts.Dispose();
    }
}
```

But this will not validate that the endpoint can successfully send message out.

To verify that an endpoint can send messages on a periodic base, I would recommend either to look into ServiceControl with Heartbeats plugin or mimic what it does (get an `IBus`, try to send a message and see if the operation is failing. And even then, you'd need to handle those message so that they don't build up and clutter your queue/namespace).

I have [raised a PR](https://github.com/Particular/docs.particular.net/pull/2438) to the documentation to make it clear that scheduler can be interrupted.

NSB.ASB utilizes native ASB client retries along with its own. Once all of those retries are exceeded, NSB.ASB will bubble up the error. At that point, Scheduler API that is using NSB handler to implement scheduling will take advantage of immediate and delayed retries. Once those are exhausted, scheduling message will be forwarded o the error queue (assuming, ASB is working). There is nothing that the transport can do at this point.

**Comment by SeanFeldman** [comment] 2017-06-30 14:32
Closing this one. The VM doesn't even exist anymore.

**Closed by SeanFeldman** 2017-06-30 14:32 UTC
Labels: State: Blocked, Withdrawn: Won't Fix
